name: vlibras_player_example
description: Demonstrates all features of the vlibras_player plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vlibras_player:
    path: ..
  libras_keyboard:
    path: ../../libras_keyboard

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
